name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v3.0.8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has been open 30 days with no activity."
          stale-pr-message: "This pull request has been automatically marked as stale because it has been open 30 days with no activity."
          stale-issue-label: "stale-issue"
          exempt-issue-labels: "enhancement,documentation,good-first-issue"
          stale-pr-label: "stale-pr"
          exempt-pr-labels: "work-in-progress"
          days-before-stale: 30
          days-before-close: -1
